---
name: Convert pdfs to markdown
run-name: Convert PDFs to markdown

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  convert-pdf:
    permissions:
      contents: read # To enable linting of files in repo
      statuses: write # To report GitHub Actions status checks      
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4.2.2

     - name: Configure Python
       uses: actions/setup-python@v5.4.0
       with:
         python-version: '3.11'

     - name: Cache pip
       uses: actions/cache@v4.2.3
       with:
         path: ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-

     - name: Install packages
       run: | 
         pip install -r requirements.txt

     - name: Split pdf into segments
       run: |
         mkdir -p segments
         python scripts/split_pdf_by_bookmarks.py input/msp430_user_guide.pdf segments

     - name: Convert PDF to markdown
       run: |
         mkdir -p output
         marker segments --output_format markdown --output_dir output

     - name: Upload converted files
       uses: actions/upload-artifact@v4.6.2
       with:
         name: converted-markdown
         path: output
